In [49]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [50]:
### sentences

sent = ['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good']

In [51]:
voc_size = 10000

In [52]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr 

[[9853, 5987, 6293, 3246],
 [9853, 5987, 6293, 1664],
 [9853, 8184, 6293, 5741],
 [5940, 7484, 705, 9089, 7843],
 [5940, 7484, 705, 9089, 2690],
 [6760, 9853, 4012, 6293, 6231],
 [2638, 9075, 6069, 9089]]

In [53]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9853 5987 6293 3246]
 [   0    0    0    0 9853 5987 6293 1664]
 [   0    0    0    0 9853 8184 6293 5741]
 [   0    0    0 5940 7484  705 9089 7843]
 [   0    0    0 5940 7484  705 9089 2690]
 [   0    0    0 6760 9853 4012 6293 6231]
 [   0    0    0    0 2638 9075 6069 9089]]


In [54]:
dim = 10
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [55]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [58]:
embedded_docs = np.array(embedded_docs)
output = model.predict(embedded_docs)
print(output)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[[ 0.0054059   0.00076591 -0.03065079  0.04763181  0.024669
   -0.02156445 -0.01481986  0.03115858 -0.01280411 -0.01752286]
  [ 0.0054059   0.00076591 -0.03065079  0.04763181  0.024669
   -0.02156445 -0.01481986  0.03115858 -0.01280411 -0.01752286]
  [ 0.0054059   0.00076591 -0.03065079  0.04763181  0.024669
   -0.02156445 -0.01481986  0.03115858 -0.01280411 -0.01752286]
  [ 0.0054059   0.00076591 -0.03065079  0.04763181  0.024669
   -0.02156445 -0.01481986  0.03115858 -0.01280411 -0.01752286]
  [ 0.01253218  0.01214061 -0.01212283 -0.04721714 -0.02054465
   -0.04945182 -0.01421248  0.03892023  0.02864424  0.02450925]
  [-0.01320664 -0.03522562  0.01576707 -0.01125596  0.03166157
   -0.00421939 -0.04640597 -0.04568224 -0.0042133   0.04129148]
  [ 0.02989886 -0.04412825 -0.04714196  0.00728476  0.02856434
    0.0296955  -0.01642608 -0.02857265 -0.02194909 -0.01042219]
  [-0.00555345 -0.01023472 -0.01372545 -0.01289045  0.02635344
   -0.03116087 -0.

In [60]:
model.predict(embedded_docs)[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([ 0.0054059 ,  0.00076591, -0.03065079,  0.04763181,  0.024669  ,
       -0.02156445, -0.01481986,  0.03115858, -0.01280411, -0.01752286],
      dtype=float32)